config/routes.rb
Rails.application.routes.draw do
  
    root to: 'sessions#welcome'

    resources :users, only: [:new, :create, :homepage, :profile]

    
    get '/login' => 'sessions#new'
    post '/login' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
  
    get '/signup' => 'users#new' 
    post '/signup' => 'users#create'
   

    get '/biaslist', to: 'biaslists#mybias', as: "my_bias"

    match '/auth/:google_oauth2/callback' => 'sessions#google', via: [:get,:post]

   

    resources :groups, only: [:index, :show] 
   
    resources :kpopidols, only: [:index, :show] do
      resources :biaslists
    end

    
    
    

    
    




    
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/biaslist.rb
class Biaslist < ApplicationRecord
    belongs_to :user
    belongs_to :kpopidol

end

app/models/group.rb
class Group < ApplicationRecord
    has_many :kpopidols

    has_many :users, through: :checkout_lists

    has_many :referalls, class_name: "Group",
    foreign_key: "recommendation_id"

    belongs_to :recommendation, class_name: "Group", optional: true

    def self.main_group
        self.where({ name: ["Stray Kids", "Monsta X", "BigBang", "NCT 127", "Got7"]})
    end

    def self.recommended_groups
        self.referalls
    end

    

   
end

app/models/kpop_idol.rb
class KpopIdol < ApplicationRecord
    belongs_to :group
    has_many :biaslists
    has_many :users, through: :biaslists
end

app/models/kpopidol.rb
class Kpopidol < ApplicationRecord
    belongs_to :group
    has_many :biaslists
    has_many :users, through: :biaslists
end

app/models/user.rb
class User < ApplicationRecord
    has_many :biaslists
    has_many :kpopidols, through: :biaslists 

    has_many :groups, through: :checkout_lists

    has_secure_password
    validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  private

 def current_user
    User.find(session[:user_id])
 end


  def logged_in?
      !!session[:user_id]
  end


 

 

end

app/controllers/biaslists_controller.rb
class BiaslistsController < ApplicationController

  before_action :set_biaslist, only: [:show, :edit, :update, :destroy]
  before_action :set_kpopidol, only: [:new, :show, :edit ]

  def new
   
    @biaslist = @kpopidol.biaslists.build
     render :new

  end

  def mybias
    if logged_in?
      @biaslist = current_user.biaslists 
      render :my_bias
    else
      redirect_to login_path
    end
  end

  def show
    if logged_in?
     
      render :show
    else
      redirect_to login_path
    end
  end

  def create
   
    @biaslist = Biaslist.new(bias_params)
      @biaslist.save
      redirect_to my_bias_path      
  end

  def edit
    if logged_in?
     
      if  @biaslist.user_id == current_user.id 
          render :edit

      else 
      redirect_to login_path
      end
    end 
  end

  

  def update
  
      @biaslist.update(notes: params[:biaslist][:notes])
      redirect_to my_bias_path
  end

  def destroy
    
    if  @biaslist.user_id == current_user.id
        @biaslist.destroy
        
        redirect_to my_bias_path
    end
    
  end

  private 
  def bias_params
   params.require(:biaslist).permit(:notes,:user_id,:kpopidol_id)
  end 

  def set_biaslist
    @biaslist = Biaslist.find(params[:id])
  end

  def set_kpopidol
    @kpopidol = Kpopidol.find(params[:kpopidol_id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  def index
    @groups = Group.all
  end

  def show 
    @group = Group.find(params[:id])
  end

  def main_group
    @groups = Group.main_group
    render :index 

  end

  def recommended_groups
    @groups = Group.recommended_groups
  end

  
    




end

app/controllers/kpopidols_controller.rb
class KpopidolsController < ApplicationController

  def index
    @kpopidols = Kpopidol.all 
    render :index 
  end

  def show
    @kpopidol = Kpopidol.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def welcome
        
    end

    def new
        @user = User.new
        
    end

    def create 
        @user = User.find_by(username:params[:username])
        if !@user
          @error = "Are you sure that's your username?"
          render :new
        elsif !@user.authenticate(params[:password])
          @error =  "Password no matchy records"
          render :new  
        else 
          session[:user_id] = @user.id
          redirect_to groups_path 
        end 
    end

    def google 
    
      user = User.find_or_create_by(username: auth["info"]["name"], uid: auth["uid"]) do |user|
          user.password = SecureRandom.hex(10)
         
      end
    

      if user
          session[:user_id] = user.id  
          redirect_to groups_path
      else
          
          redirect_to login_path
      end
     
  end

  def destroy 
      session.delete(:user_id)
      redirect_to login_path
  end

  

  private 

  def auth 
      request.env['omniauth.auth']
  end


   

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     

  def new
    @user = User.new
   
  end

  def create
      @user = User.new(user_params)
     
      if @user.save 
          session[:user_id] = @user.id
          redirect_to groups_path
      else
          render :new
      end 
    end
  end
  
  def profile

  end




private 
def user_params
  params.require(:user).permit(:username,:password)
end 

def destroy
      @user = User.find(params[:id])
      @user.destroy
      redirect_to login_path
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!current_user
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end
end

app/helpers/biaslists_helper.rb
module BiaslistsHelper
end

app/helpers/checkout_lists_helper.rb
module CheckoutListsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/idols_helper.rb
module IdolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/biaslists/_form.html.erb
<%= form_for biaslist, url:url do |f| %>
  <div>
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>
  <div>
    <%= f.hidden_field :kpopidol_id, :value => kpopidol.id %>
  </div>
  <div>
    <%= f.label :note %>
    <%= f.text_area :notes %>
  </div>
  <%= f.submit %>
<% end %>

app/views/biaslists/edit.html.erb
<h1>Edit Bias Nickname</h1>

<%= render partial: 'form', locals: {biaslist: @biaslist, url: kpopidol_biaslist_path(@kpopidol, @biaslist), kpopidol:@kpopidol}%>

app/views/biaslists/my_bias.html.erb
<h3>List of Male Bias Idols</h3>

<% @biaslist.each do |b| %>
<h2><%= link_to b.kpopidol.stage_name, kpopidol_biaslist_path(b.kpopidol.id, b.id) %> </h2>



<% end %>

app/views/biaslists/new.html.erb
<h1>Create Bias Nickname</h1>

<%= render partial: 'form', locals: {biaslist: @biaslist, url: kpopidol_biaslists_path(@kpopidol, @biaslist), kpopidol:@kpopidol}%>

app/views/biaslists/show.html.erb
<h1>Bias Info</h1>

<h2>Profile: <%= link_to @biaslist.kpopidol.stage_name, kpopidol_path(@biaslist.kpopidol.id) %> </h2>

<h2> Nickname: <%= @biaslist.notes %>


<br>
<p><%= button_to "Edit Nickname", edit_kpopidol_biaslist_path(@biaslist.kpopidol.id, @biaslist.id), method: "get" %> </p>

<p><%= button_to "Remove", kpopidol_biaslist_path(@biaslist.kpopidol.id, @biaslist.id), method: 'delete' %> </p>
 

app/views/groups/index.html.erb
<h1> Groups </h1>
<br>
<br>
<% @groups.main_group.each do |group| %>
<p><%= link_to group.name, group_path(group.id) %> </p>





<% end %> 

app/views/groups/show.html.erb
<h1><%= @group.name %></h1><br>
<br>
<h2> Fandom Name: <%= @group.fandom_name %> </h2>
<h2> Debut Date: <%= @group.debut_date %> </h2>
<h2> <%= link_to "Instagram", @group.instagram %>
<h2> <%= link_to "Twitter", @group.twitter %>
<h2> <%= link_to "Youtube", @group.youtube %>
<br>
<br>
<iframe width="560" height="315" src="<%= @group.live_video %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
<br>

<br>
<br>
<% @group.kpopidols.each do |idol| %>
<p><%= link_to idol.stage_name, kpopidol_path(idol.id) %> </p>
<% end %> 



<h2> Recommended Music: </h2>
<% @group.referalls.each do |refer| %>

<p><%= link_to refer.name, group_path(refer.id) %> </p>
<% end %> 

app/views/kpopidols/index.html.erb
<h1> Idols </h1>

<% @kpopidols.each do |idol| %>
<p><%= link_to idol.stage_name, kpopidol_path(idol.id) %> </p>


<% end %> 

app/views/kpopidols/show.html.erb
<h1> <%= @kpopidol.stage_name %> </h1>
<br>

<a><img alt="meme" src="<%= @kpopidol.member_img %>"
width="450" height="450"></a>
<br>
<h4> Birth Name: <%= @kpopidol.birth_name %> </h4>
<h4> Birthday: <%= @kpopidol.birthday %> </h4>
<h4> Birth Place: <%= @kpopidol.birth_place %> </h4>
<h4> Height: <%= @kpopidol.height %> </h4>
<h4> Position: <%= @kpopidol.position %> </h4>
<h4> Nickname: <%= @kpopidol.nickname %> </h4>
<h4> Famous Quote: <%= @kpopidol.famous_quote %> </h4>
<br>
<br>
<iframe width="560" height="315" src="<%= @kpopidol.fan_cam %>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

<br>
<br>

<%= button_to "Add Bias", new_kpopidol_biaslist_path(@kpopidol.id), method: "get" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroToRailsModelsAndRestfulRouting</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
  <nav>
      <ul>
      <%if logged_in? %>
          <li><%= link_to("Home", root_path) %></li>
          <li><%= link_to("Groups", groups_path) %></li>
          <li><%= link_to("Bias List", my_bias_path) %></li>
          <li><%= button_to("Logout", logout_path, method: 'delete') %></li>
          <% else %>
          <li><%= button_to  "Log in with Google", '/auth/google_oauth2' %> </li>
          <li><%= link_to("Sign Up", signup_path) %></li>
          <li><%= link_to("Login", login_path) %></li>
          
        <% end %>
      </ul>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<br>
<br>
<br>
<br>
<br>
<div class="container">
  <h1 style="color: #2E1114; text-align:center">Sign Up!</h1>
  <div style="color: #2E1114; text-align:center">
  <% @user.errors.full_messages.each do |e| %>
  <h2> <%= e %> </h2>
  <% end  %>
    <%= form_for @user, url: signup_path  do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %> <br>
    <%= f.label :password %>
    <%= f.password_field :password%> <br>
    <%= f.submit "Remember Me!" %>
    <% end %>
    </div>
</div>
    <style>